const fs = require('fs');
const path = require('path');

const questions = [
  // ROUND 1 - 10 Questions
  {
    "id": "R1-Q01",
    "round": 1,
    "language": "python",
    "title": "Missing Colon",
    "description": "This function is supposed to print 'Hello' if x is true, but there is a syntax error.",
    "bugDescription": "Missing colon after if condition.",
    "buggyCode": "def greet(x):\n    if x\n        print('Hello')",
    "correctSolution": "def greet(x):\n    if x:\n        print('Hello')",
    "expectedOutput": "Hello",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "True", "expectedOutput": "Hello", "description": "Test true" }]
  },
  {
    "id": "R1-Q02",
    "round": 1,
    "language": "python",
    "title": "Incorrect Array Declaration",
    "description": "Create a list containing numbers 1, 2, 3. The current syntax is wrong.",
    "bugDescription": "Used {} instead of [] for a list.",
    "buggyCode": "nums = {1, 2, 3}\nprint(nums[0])",
    "correctSolution": "nums = [1, 2, 3]\nprint(nums[0])",
    "expectedOutput": "1",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "1", "description": "Index 0" }]
  },
  {
    "id": "R1-Q03",
    "round": 1,
    "language": "python",
    "title": "Wrong Variable Name",
    "description": "Print the variable message, but there is a typo.",
    "bugDescription": "Used 'Massage' instead of 'message'.",
    "buggyCode": "message = 'Welcome'\nprint(Massage)",
    "correctSolution": "message = 'Welcome'\nprint(message)",
    "expectedOutput": "Welcome",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "Welcome", "description": "Print text" }]
  },
  {
    "id": "R1-Q04",
    "round": 1,
    "language": "python",
    "title": "Incorrect Variable in Loop",
    "description": "Print numbers 0 to 2 using a for loop. It prints the loop iterable instead of the variable.",
    "bugDescription": "Used 'i' instead of the loop variable 'j'.",
    "buggyCode": "i = 5\nfor j in range(3):\n    print(i)",
    "correctSolution": "for j in range(3):\n    print(j)",
    "expectedOutput": "0\n1\n2",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "0\n1\n2", "description": "Loop print" }]
  },
  {
    "id": "R1-Q05",
    "round": 1,
    "language": "python",
    "title": "Missing Bracket",
    "description": "Call the print function with a string, but a bracket is missing.",
    "bugDescription": "Missing closing parenthesis.",
    "buggyCode": "print('Bugwest'",
    "correctSolution": "print('Bugwest')",
    "expectedOutput": "Bugwest",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "Bugwest", "description": "Print string" }]
  },
  {
    "id": "R1-Q06",
    "round": 1,
    "language": "python",
    "title": "Simple Syntax Error",
    "description": "Assign the value 10 to a variable and print it. The assignment operator is wrong.",
    "bugDescription": "Used == instead of =.",
    "buggyCode": "x == 10\nprint(x)",
    "correctSolution": "x = 10\nprint(x)",
    "expectedOutput": "10",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "10", "description": "Assign and print" }]
  },
  {
    "id": "R1-Q07",
    "round": 1,
    "language": "python",
    "title": "Basic Logic Mistake",
    "description": "The function should add 2 to the input, but it subtracts 2 instead.",
    "bugDescription": "Used - instead of +.",
    "buggyCode": "def add_two(x):\n    return x - 2",
    "correctSolution": "def add_two(x):\n    return x + 2",
    "expectedOutput": "7",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "5", "expectedOutput": "7", "description": "Add 2" }]
  },
  {
    "id": "R1-Q08",
    "round": 1,
    "language": "python",
    "title": "Simple Condition Mistake",
    "description": "Return True if x is greater than 10. The condition currently returns True if x is less than 10.",
    "bugDescription": "Used < instead of >.",
    "buggyCode": "def is_greater_than_10(x):\n    return x < 10",
    "correctSolution": "def is_greater_than_10(x):\n    return x > 10",
    "expectedOutput": "True",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "15", "expectedOutput": "True", "description": "Check condition" }]
  },
  {
    "id": "R1-Q09",
    "round": 1,
    "language": "python",
    "title": "Simple Loop Mistake",
    "description": "Calculate the sum of numbers from 1 to 3. The loop stops too early.",
    "bugDescription": "Range needs to go to 4.",
    "buggyCode": "total = 0\nfor i in range(1, 3):\n    total += i\nprint(total)",
    "correctSolution": "total = 0\nfor i in range(1, 4):\n    total += i\nprint(total)",
    "expectedOutput": "6",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "6", "description": "Sum 1 to 3" }]
  },
  {
    "id": "R1-Q10",
    "round": 1,
    "language": "python",
    "title": "Meaningful Indentation Mistake",
    "description": "Print 'Done' only after the loop completes. Currently it prints during the loop.",
    "bugDescription": "print('Done') is inside the loop instead of outside.",
    "buggyCode": "for i in range(2):\n    print(i)\n    print('Done')",
    "correctSolution": "for i in range(2):\n    print(i)\nprint('Done')",
    "expectedOutput": "0\n1\nDone",
    "marks": 5,
    "difficulty": "Easy",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "0\n1\nDone", "description": "Loop then print" }]
  },

  // ROUND 2 - 5 Questions
  {
    "id": "R2-Q01",
    "round": 2,
    "language": "python",
    "title": "For Loop Error",
    "description": "Create a list of squares of numbers from 0 to 4 using a for loop. The loop variable is wrong.",
    "bugDescription": "Used 'i * 2' instead of 'i * i'.",
    "buggyCode": "squares = []\nfor i in range(5):\n    squares.append(i * 2)\nprint(squares)",
    "correctSolution": "squares = []\nfor i in range(5):\n    squares.append(i * i)\nprint(squares)",
    "expectedOutput": "[0, 1, 4, 9, 16]",
    "marks": 10,
    "difficulty": "Medium",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "[0, 1, 4, 9, 16]", "description": "Squares list" }]
  },
  {
    "id": "R2-Q02",
    "round": 2,
    "language": "python",
    "title": "Function Return Value",
    "description": "The function should return the product of a and b, but it returns nothing.",
    "bugDescription": "Missing 'return' keyword.",
    "buggyCode": "def multiply(a, b):\n    a * b\n\nprint(multiply(3, 4))",
    "correctSolution": "def multiply(a, b):\n    return a * b\n\nprint(multiply(3, 4))",
    "expectedOutput": "12",
    "marks": 10,
    "difficulty": "Medium",
    "visibleTestCases": [{ "id": "tc-1", "input": "", "expectedOutput": "12", "description": "Multiply two numbers" }]
  },
  {
    "id": "R2-Q03",
    "round": 2,
    "language": "python",
    "title": "If/Else Logic",
    "description": "Return 'Even' if a number is even, else 'Odd'. The logic is inverted.",
    "bugDescription": "Modulo logic is flipped.",
    "buggyCode": "def check_even(n):\n    if n % 2 != 0:\n        return 'Even'\n    else:\n        return 'Odd'",
    "correctSolution": "def check_even(n):\n    if n % 2 == 0:\n        return 'Even'\n    else:\n        return 'Odd'",
    "expectedOutput": "Even",
    "marks": 10,
    "difficulty": "Medium",
    "visibleTestCases": [{ "id": "tc-1", "input": "4", "expectedOutput": "Even", "description": "Check even number" }]
  },
  {
    "id": "R2-Q04",
    "round": 2,
    "language": "python",
    "title": "Write Code: Multiply by 10",
    "description": "Write a 1-line function to multiply the input 'n' by 10 and return it.",
    "bugDescription": "Empty function.",
    "buggyCode": "def multiply_by_10(n):\n    # Write your code here",
    "correctSolution": "def multiply_by_10(n):\n    return n * 10",
    "expectedOutput": "50",
    "marks": 10,
    "difficulty": "Medium",
    "visibleTestCases": [{ "id": "tc-1", "input": "5", "expectedOutput": "50", "description": "Multiply by 10" }]
  },
  {
    "id": "R2-Q05",
    "round": 2,
    "language": "python",
    "title": "Write Code: First Element",
    "description": "Write a 1-line function that returns the first element of the given list 'lst'.",
    "bugDescription": "Empty function.",
    "buggyCode": "def get_first(lst):\n    # Write your code here",
    "correctSolution": "def get_first(lst):\n    return lst[0]",
    "expectedOutput": "99",
    "marks": 10,
    "difficulty": "Medium",
    "visibleTestCases": [{ "id": "tc-1", "input": "[99, 88, 77]", "expectedOutput": "99", "description": "Return first element" }]
  }
];

const dest = path.join(__dirname, 'server', 'questionsData.json');
fs.writeFileSync(dest, JSON.stringify(questions, null, 2), 'utf-8');
console.log('Successfully updated questionsData.json');
